---
# Rename file to secrets.yml to get started for development or test

development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: ND3mZpWrmpAEEjke2N7eJn65IrUPLtCxwYSaql1b0L0+LgaxMPik2Eb9DEYsNSV4SWC4FCOdKtsQ8IIangRYDQ==
  MSG_KEY: Ri5Jto03ZB60i6WWVlo9MnBE1Ivc27Lr1HwHckoWARI=
  REDIS_URL: redis://:pf36cc99333e177905a61b7c41f47ed46c140dd1555f3917a8289469ed9d862d1@ec2-54-163-171-22.compute-1.amazonaws.com:16359
  GH_OAUTH_URL: https://github.com/login/oauth/authorize
  GH_TOKEN_URL: https://github.com/login/oauth/access_token
  GH_SCOPE: user:email
  GH_CLIENT_ID: <provision ID/SECRET on Github>
  GH_CLIENT_SECRET: <provision ID/SECRET on Github>
  # google
  GO_SCOPE: user:email
  GO_CLIENT_ID: <provision ID/SECRET on Google>
  GO_CLIENT_SECRET: <provision ID/SECRET on Google>

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: ND3mZpWrmpAEEjke2N7eJn65IrUPLtCxwYSaql1b0L0+LgaxMPik2Eb9DEYsNSV4SWC4FCOdKtsQ8IIangRYDQ==
  MSG_KEY: Ri5Jto03ZB60i6WWVlo9MnBE1Ivc27Lr1HwHckoWARI=
  REDIS_URL: redis://:pf36cc99333e177905a61b7c41f47ed46c140dd1555f3917a8289469ed9d862d1@ec2-54-163-171-22.compute-1.amazonaws.com:16359
  GH_OAUTH_URL: https://github.com/login/oauth/authorize
  GH_TOKEN_URL: https://github.com/login/oauth/access_token
  GH_SCOPE: user:email
  GH_CLIENT_ID: <provision ID/SECRET on Github>
  GH_CLIENT_SECRET: <provision ID/SECRET on Github>
  # google
  GO_SCOPE: user:email
  GO_CLIENT_ID: <provision ID/SECRET on Google>
  GO_CLIENT_SECRET: <provision ID/SECRET on Google>

production:
  API_URL: <provisioned API URL (ending with api/[version])...>
  APP_URL: <provisioned app URL (root without ending slash)>
  SESSION_SECRET: ND3mZpWrmpAEEjke2N7eJn65IrUPLtCxwYSaql1b0L0+LgaxMPik2Eb9DEYsNSV4SWC4FCOdKtsQ8IIangRYDQ==
  MSG_KEY: Ri5Jto03ZB60i6WWVlo9MnBE1Ivc27Lr1HwHckoWARI=
  REDIS_URL: rediss://:pf36cc99333e177905a61b7c41f47ed46c140dd1555f3917a8289469ed9d862d1@ec2-54-163-171-22.compute-1.amazonaws.com:16360
  REDIS_TLS_URL: rediss://:pf36cc99333e177905a61b7c41f47ed46c140dd1555f3917a8289469ed9d862d1@ec2-54-163-171-22.compute-1.amazonaws.com:16360
  GH_OAUTH_URL: https://github.com/login/oauth/authorize
  GH_TOKEN_URL: https://github.com/login/oauth/access_token
  GH_SCOPE: user:email
  GH_CLIENT_ID: <provision ID/SECRET on Github>
  GH_CLIENT_SECRET: <provision ID/SECRET on Github>
  # google
  GO_OAUTH_URL: 
  GO_TOKEN_URL:
  GO_SCOPE: user:email
  GO_CLIENT_ID: <provision ID/SECRET on Google>
  GO_CLIENT_SECRET: <provision ID/SECRET on Google>